### PR TITLE
Gremlin like builder

### PR DESCRIPTION
**Pull request by Fulnir**
Added an alternate docker-compose.yml file for 3 dgraph instances(dev,test,prod)
(Attention! These using some other ports. 9092 for the test server and 8088 for ratel)

Added first gremlin functions like _Graph Traversal Steps_. [Gremlin AddVertex Step](http://tinkerpop.apache.org/docs/current/reference/#addvertex-step) and AddProperty Step

`
   {:ok, channel} = GRPC.Stub.connect(Application.get_env(:exdgraph, :dgraphServerGRPC))
   {:ok, graph} = Graph.new(channel)

    graph
    |> addV(Toon)
    |> property("name", "Bugs Bunny")
    |> property("type", "Toon")`

And some tests

### CODE REVIEW

**Comment by ospaarmann** [comment]
Hey @Fulnir 

thank you for your contribution! But I am not quite sure what to do with it right now. First priority is to establish a stable way to connect to the dgraph server. I started implementing the [DBConnection behaviour](https://hexdocs.pm/db_connection/DBConnection.html) to achieve that. This and supporting regular GraphQL+ queries, mutations etc. is the first thing to to in my pov.

**About Gremlin support in general. [The DGraph docs state](https://docs.dgraph.io/dgraph-compared-to-other-databases/)**

> Neo4j supports Cypher and Gremlin query language. Dgraph supports GraphQL+-, a variation of GraphQL, a query language created by Facebook. As opposed to Cypher or Gremlin, which produce results in simple list format, GraphQL allows results to be produced in a subgraph format, which has richer semantics. Also, GraphQL supports schema validation which is useful to ensure data correctness during both input and output.
> 
> While GraphQL is modern, Gremlin and Cypher are a lot more popular. Dgraph plans to support them after v1.0.

So as far as I see Gremlin isn't even supported yet. But I'm open to input and discussion.

Thanks,
Ole

**Comment by Fulnir** [comment]
The goal is alternate functions to support queries and mutations.
In my own dgraph client(under development) I can mutate a struct in this way:

```
person = %Person{person_id: "Edwin", name: "Ed", alchemist: true, gender: :male, age: 99}
{:ok, edwin_node} = mutate_node_from_struct(person)
```
     
Or in a gremlin style:
```
{:ok, edwin_vertex} =
    graph
    |> addV(Person)
    |> property("person_id", "Edwin")
    |> property("name", "Ed")
    |> property("alchemist", true)
```

BTW, on my local machine, all tests are green. But not with travis-ci. I have no idea why!

**Comment by ospaarmann** [comment]
That looks interesting. But I first want to have a stable DBConnection implementation before going into the direction of Gremlin. I hope you understand. But it looks like a very nice addition!

Are you interested in helping with the basics? That would get us quicker in the direction of adding Gremlin.

About travis-ci: I accidentally added the `docker-compose.yml` to the `.gitignore` file, which caused it to fail. I removed it again a bit late. Maybe this was the issue?

**Comment by Fulnir** [comment]
I move the gremlin code in an extra repository.
Then I close my pull request. Later I make a new one with some basics but without the gremlin code.

**Pull request closed without merging**
