### PR TITLE
2 more query functions

### PR DESCRIPTION
**Pull request by Fulnir**
`query(conn, "anyofterms", "name", "VI")`
```
query(
        conn,
        "anyofterms",
        "name",
        "VI",
        "uid name release_date starring { name }"
      )
```
**removed**: import_starwars_sample() from mutation_test setup (double mutation)

### CODE REVIEW

**Comment by ospaarmann** [comment]
Hey,

I am not sure if this is the way to go since queries can become pretty complex. I think we should first discuss a good way to model GraphQL+ queries in Elixir before going down a specific route or implementing specific query functions for certain types of GraphQL+ functions.

[Take this example from Manish Rai Jains talk](https://youtu.be/cHXbYLNa0qQ?t=12m43s)

**Comment by Fulnir** [comment]
I think it's good to have a few levels of access.

the graphql level
`query(conn, "{ starwars(func: anyofterms(name, "VI")) { uid name starring{ name } } }")`

some quick and easy queries
`query(conn, "anyofterms", "name", "VI")`

and a query builder like this **_draft concept_**
```
    graph_query = GraphQL.graph_query(conn, "starwars")
    graph_query
    |> query_root(:allofterms, {"name", "Star Wars"})
    |> first(2)
    |> filter(:has, "genre")
    |> filter(:or, :le, {"production-cost", "20000000"})
    |> order(:desc, "initial_release_date")
    |> return(["uid")
    |> return(["name", "initial_release_date"])
    |> return_expand("director.film")
    |> filter_expand(:le, {initial_release_date, "2000"})
    |> return_expand(["name@en", "initial_release_date"])
    |> query()
```

**Comment by ospaarmann** [comment]
So I had a look at your PR again. Thank you! I think having more query functions is in general a good idea. But there are a couple of issues.

- There are still IO.inspect calls in the code
- Your implementation puts `object` always in quotes, assuming that it is always a string. This will not work with some functions (`eq()`, `gt()`, `lt()`, etc.)
- The `display` parameter should have a default value
- It is not possible to select multiple predicates that should be returned (if I'm not mistaken)
- Some query functions don't have an arity of 2, for example `uid()`
- It doesn't support pagination like `me(func: has(director.film), first: 5)`
- It doesn't support sorting

This might seem like much. But I don't want people to start using a function and then suddenly change the API and break their application. So I would rather try to go for a more complete integration.

What do you think?

**Comment by ospaarmann** [comment]
I think a good way to handle this is this client: https://github.com/elbow-jason/dgraph_ex

**Comment by ospaarmann** [comment]
And @Fulnir can we please have a discussion on here first before you submit a PR?

**Comment by Fulnir** [comment]
To avoid new commits appearing here, I closed the pull request.

**Pull request closed without merging**
